# Generated by Django 5.2.5 on 2025-08-23 18:42

import django.core.validators
import django.db.models.deletion
import labcerti.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('inn', models.CharField(max_length=15, unique=True)),
                ('registrar', models.CharField(max_length=255, verbose_name="Ro'yxatdan o'tkazuvchi organ")),
                ('registration_date', models.DateField(verbose_name="Davlat ro'yxatidan o'tkazilgan sana")),
                ('registration_number', models.CharField(max_length=255, verbose_name="Davlat ro'yxatidan o'tkazilgan raqami")),
                ('legal_form', models.CharField(max_length=255, verbose_name='Tashkiliy-huquqiy shakli')),
                ('ifut_code', models.CharField(max_length=255, verbose_name='IFUT kodi')),
                ('dbibt_code', models.CharField(max_length=255, verbose_name='DBIBT kodi')),
                ('small_business', models.BooleanField(default=False, verbose_name="Kichik tadbirkorlik sub'ektlariga mansubligi")),
                ('status', models.CharField(max_length=255, verbose_name='Faollik holati')),
                ('charter_fund', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ustav fondi')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Elektron pochta manzili')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aloqa telefoni')),
                ('mho_code', models.CharField(max_length=255, verbose_name='MHOBT kodi')),
                ('address', models.TextField(verbose_name="Ko'cha, uy, xonadon")),
                ('director_name', models.CharField(max_length=255, verbose_name='Rahbarning F.I.SH.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('approver', 'Approver')], default='creator', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', "Telefon raqami to'g'ri formatda emas.")])),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas')], default='active', max_length=20, verbose_name='Faollik holati')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='GUVOHNOMASI', max_length=255, verbose_name='Hujjat turi')),
                ('certificate_number', models.CharField(max_length=255, unique=True, verbose_name='Guvohnoma raqami')),
                ('comparison_date', models.DateField(verbose_name='Qiyoslash sanasi')),
                ('valid_until_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('standards_used', models.TextField(verbose_name='Etalonlar va vositalar')),
                ('service_provider_name', models.CharField(max_length=255, verbose_name='Metrologiya xizmati nomi')),
                ('metrologist_name', models.CharField(max_length=255, verbose_name='Qiyoslovchi')),
                ('owner_inn', models.CharField(max_length=255, verbose_name='Tashkilot INNsi')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Tayyorlovchi')),
                ('origin_country', models.CharField(max_length=255, verbose_name='Ishlab chiqarilgan davlat')),
                ('measurement_range', models.CharField(max_length=255, verbose_name="O'lchash oralig'i")),
                ('error_limit', models.CharField(max_length=255, verbose_name='Xatolik chegaralari')),
                ('device_name', models.CharField(max_length=255, verbose_name="O'lchash vositasining nomi")),
                ('device_serial_numbers', models.CharField(max_length=255, verbose_name='Zavod raqami')),
                ('comparison_methodology_doc', models.CharField(max_length=255, verbose_name='Qiyoslash uslubiyati')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Holati')),
                ('protocol_file', models.FileField(blank=True, null=True, upload_to='data/labcerti/protocols/', validators=[labcerti.models.validate_file_size], verbose_name='Protokol fayli')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='data/labcerti/certificates/', verbose_name='Sertifikat fayli')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='data/labcerti/qr_codes/', verbose_name='QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rad etilgan sana')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labcerti.organization', verbose_name='Egasi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to='labcerti.userprofile', verbose_name='Tasdiqladi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to='labcerti.userprofile', verbose_name='Yaratdi')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_certificates', to='labcerti.userprofile', verbose_name='Rad etdi')),
            ],
        ),
    ]
