# Generated by Django 5.2.5 on 2025-08-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_center_user',
            field=models.BooleanField(default=False),
        ),
    ]
