# Generated by Django 5.2.5 on 2025-08-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0002_userprofile_is_center_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name="Ko'cha, uy, xonadon"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='charter_fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='lank=TrueUstav fondi'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dbibt_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DBIBT kodi'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rahbarning F.I.SH.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ifut_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IFUT kodi'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tashkiliy-huquqiy shakli'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mho_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MHOBT kodi'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registrar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ro'yxatdan o'tkazuvchi organ"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Davlat ro'yxatidan o'tkazilgan sana"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Davlat ro'yxatidan o'tkazilgan raqami"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Faollik holati'),
        ),
    ]
