# Generated by Django 5.2.5 on 2025-08-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0003_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_certificates', to='labcerti.userprofile', verbose_name='Rad etdi'),
        ),
    ]
