# Generated by Django 5.2.5 on 2025-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0004_alter_certificate_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='comparison_document',
            field=models.CharField(blank=True, null=True, verbose_name="qiyoslash bo'yicha xujjatning belgilanishi va nomlanishi"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner_inn',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarining egasi - yuridik shaxs INNsi"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarining egasi - yuridik shaxs nomi"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='service_provider_name',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarini qiyoslagan metrologiya xizmatining nomi"),
        ),
    ]
