# Generated by Django 5.2.5 on 2025-08-24 14:03

import django.core.validators
import labcerti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0005_certificate_comparison_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='comparison_methodology_doc',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalariga qo'yiladigan talablarni reglamentlovchi normativ xujjat belgilanishi va nomi"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='error_limit',
            field=models.CharField(max_length=255, verbose_name='Xatolik chegaralari, aniqlik klassi'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarini tayyorlovchi"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='measurement_range',
            field=models.CharField(max_length=255, verbose_name="o'lchash vositalari parametrlarining nomi, o'lchashlar"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='origin_country',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarining tayyorlovchi - import qiluvchi mamlakat"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='protocol_file',
            field=models.FileField(blank=True, null=True, upload_to='data/labcerti/protocols/', validators=[labcerti.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Protokol fayli'),
        ),
    ]
