# Generated by Django 5.2.5 on 2025-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0006_alter_certificate_comparison_methodology_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='comparison_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qiyoslash sanasi'),
        ),
    ]
