# Generated by Django 5.2.5 on 2025-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0007_alter_certificate_comparison_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Guvohnoma raqami'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarini tayyorlovchi (ishlab chiqaruvchi)"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='origin_country',
            field=models.CharField(max_length=255, verbose_name="O'lchash vositalarining tayyorlovchi (ishlab chiqaruvchi) - import qiluvchi mamlakat"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner_inn',
            field=models.CharField(max_length=255, unique=True, verbose_name="O'lchash vositalarining egasi - yuridik shaxs INNsi"),
        ),
    ]
