# Generated by Django 5.2.5 on 2025-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0008_alter_certificate_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='owner_inn',
            field=models.PositiveIntegerField(unique=True, verbose_name="O'lchash vositalarining egasi - yuridik shaxs INNsi"),
        ),
    ]
