# Generated by Django 5.2.5 on 2025-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0009_alter_certificate_owner_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='service_provider_name',
            field=models.CharField(default='Geodezik metrologiya xizmat markazi', max_length=255, verbose_name="O'lchash vositalarini qiyoslagan metrologiya xizmatining nomi"),
        ),
    ]
