# Generated by Django 5.2.5 on 2025-08-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0010_alter_certificate_service_provider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='metrologist_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='metrologist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrologist_certificates', to='labcerti.userprofile', verbose_name='Qiyoslovchi'),
        ),
    ]
