# Generated by Django 5.2.5 on 2025-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0012_remove_certificate_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('approver', 'Approver'), ('administrator ', 'Administrator ')], default='creator', max_length=20),
        ),
    ]
