# Generated by Django 5.2.5 on 2025-08-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcerti', '0014_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('approver', 'Approver'), ('administrator', 'Administrator')], default='creator', max_length=20),
        ),
    ]
